POST https://127.0.0.1:8001/api/customers
Content-Type: application/json

{
  "Name": "John Doe",
  "SSN": "123",
  "accounts": [
    {
      "AccountNumber": "11111111111",
      "AccountType": "PRIVATE",
      "AccountName": "Test",
      "Currency": "USD"
    }
  ]
}

###
